kind: ConfigMap
apiVersion: v1
metadata:
  name: k8config
data:
  application.yml: |-
    greeting:
      message: Say Hello to the WorldChanges
    farewell:
      message: Say Goodbye
    ---
    spring:
      profiles: development
    greeting:
      message: Say Hello to the Developers123
    farewell:
      message: Say Goodbye to the Developers
    ---
    spring:
      profiles: production
    greeting:
      message: Say Hello to the Ops
